version: "3.7"

services:
  minio1:
    image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
    command: server --console-address ":9001" /data1
    hostname: minio1
    volumes:
      - data1-1:/data1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:
