version: "2"

services:
  minio1:
    hostname: minio1
    volumes:
      - data1-1: data1
      - data1-2: data2
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

volumes:
  data1-1:
  data1-2:
